---
- hosts: all
  become: yes
  tasks:
    - user: name=isucon groups=sudo
    - apt: name=nginx-full
    - service: name=nginx enabled=true
    - apt: name=mysql-server
    - service: name=mysql state=started enabled=true
    - apt: name=git
    - git: repo=https://github.com/isucon/isucon4.git dest=/tmp/isucon4
    - shell: cp /tmp/isucon4/qualifier/ami/files/nginx.conf /etc/nginx/nginx.conf
      notify:
        - reload nginx
    - shell: cp /tmp/isucon4/qualifier/ami/files/nginx.php.conf /etc/nginx/nginx.php.conf
    - name: copy my.cnf
      shell: cp /tmp/isucon4/qualifier/ami/files/my.cnf /etc/my.cnf
      notify:
        - restart mysqld
    - command: rm -rf /tmp/isucon
      args:
        removes: /tmp/isucon
    - file: path=/tmp/isucon state=directory
    - shell: rsync -a /tmp/isucon4/qualifier/sql /tmp/isucon/
    - shell: rsync -a /tmp/isucon4/qualifier/webapp /tmp/isucon/
    - shell: |
        cp /tmp/isucon4/qualifier/init.sh /tmp/isucon/init.sh
        chmod a+x /tmp/isucon/init.sh
    - shell: |
        cp /tmp/isucon4/qualifier/ami/files/env.sh /tmp/isucon/env.sh
        chmod a+x /tmp/isucon/env.sh
    - shell: |
        cp /tmp/isucon4/qualifier/ami/files/bashrc /home/isucon/.bashrc
        chmod a+x /home/isucon/.bashrc
    - command: chown -R isucon:isucon /tmp/isucon
    - command: rsync -avz --delete --exclude-from=/tmp/isucon4/qualifier/ami/files/rsync_exclude.txt /tmp/isucon/ /home/isucon/
      become: yes
  post_tasks:
    - name: Set Temporary password
      become: yes
      become_user: root
      blockinfile:
        create: yes
        dest: &myCnf /root/.my.cnf
        content: |
          [client]
          user = root
          password = root
          
    - command: sed -i 's/ +0900//g' /tmp/isucon/sql/dummy_log.sql.sql

    - name: Create isucon user on MySQL
      become: yes
      become_user: root
      shell: |
          mysql -uroot -proot -e "CREATE USER IF NOT EXISTS isucon@localhost IDENTIFIED BY 'isucon'; GRANT ALL PRIVILEGES ON *.* TO isucon@localhost WITH GRANT OPTION; FLUSH PRIVILEGES;"
          mysql -uroot -proot -e "DROP DATABASE IF EXISTS isu4_qualifier; CREATE DATABASE isu4_qualifier"
          mysql -uroot -proot isu4_qualifier < /tmp/isucon/sql/schema.sql
          mysql -uroot -proot isu4_qualifier < /tmp/isucon/sql/dummy_users.sql
          mysql -uroot -proot isu4_qualifier < /tmp/isucon/sql/dummy_log.sql.sql

    - name: Remove Temporary file
      become: yes
      become_user: root
      file:
        path: *myCnf
        state: absent

  handlers:
    - name: restart mysqld
      action: service name=mysql state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted
