---
- hosts: all
  become: yes
  tasks:
    - apt: pkg=git
    - apt: pkg=mercurial
    - apt: pkg=bzr
    - command: "curl -L -O  https://golang.org/dl/go1.16.5.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - command: "tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz"
      args:
        chdir: /tmp
        creates: /usr/local/go
    - shell: cp /tmp/isucon4/qualifier/ami/files/golang.sh /etc/profile.d/golang.sh
    - command: "/usr/bin/gem install -N gondler -v 0.2.0"
      args:
        creates: /usr/local/bin/gondler
    - command: /home/isucon/env.sh ./build.sh
      args:
        chdir: /home/isucon/webapp/go
    - command: chown -R isucon:isucon /home/isucon/gocode
