---
- hosts: benchservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git: repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.7.0 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby

- hosts: benchservers
  sudo: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
    # gradle
    - apt: name=gradle state=present
